; generated by PrusaSlicer 2.5.0+win64 on 2022-09-22 at 16:47:06 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.45mm

M73 P0 R4
M73 Q0 S4
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.10.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S210 ; set extruder temp
M140 S50 ; set bed temp
M190 S50 ; wait for bed temp
M109 S210 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P1 R4
M73 Q1 S4
G1 E-.8 F2100
M73 P2 R4
M73 Q2 S4
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.2
; printing object shape_002_v11.stl id:0 copy 3
G1 X158.986 Y125.245 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
;TYPE:Internal infill
;WIDTH:0.45
G1 F1200
G1 X178.719 Y125.245 E.66794
G1 X178.719 Y124.838 E.01379
M73 P3 R4
M73 Q3 S4
G1 X159.169 Y124.838 E.66174
G1 X159.169 Y124.431 E.01379
G1 X178.719 Y124.431 E.66174
G1 X178.719 Y124.023 E.01379
M73 Q4 S4
G1 X159.169 Y124.023 E.66174
G1 X159.169 Y123.616 E.01379
M73 P4 R4
G1 X178.719 Y123.616 E.66174
G1 X178.719 Y123.209 E.01379
G1 X159.169 Y123.209 E.66174
G1 X159.169 Y122.801 E.01379
M73 P5 R4
M73 Q5 S4
G1 X178.719 Y122.801 E.66174
G1 X178.719 Y122.394 E.01379
G1 X159.169 Y122.394 E.66174
G1 X159.169 Y121.987 E.01379
M73 Q6 S4
G1 X178.719 Y121.987 E.66174
G1 X178.719 Y121.58 E.01379
M73 P6 R4
G1 X159.169 Y121.58 E.66174
G1 X159.169 Y121.172 E.01379
G1 X178.719 Y121.172 E.66174
G1 X178.719 Y120.765 E.01379
M73 P7 R4
M73 Q7 S4
G1 X159.169 Y120.765 E.66174
G1 X159.169 Y120.358 E.01379
G1 X178.719 Y120.358 E.66174
G1 X178.719 Y119.95 E.01379
G1 X159.169 Y119.95 E.66174
G1 X159.169 Y119.543 E.01379
M73 P8 R4
M73 Q8 S4
G1 X178.719 Y119.543 E.66174
G1 X178.719 Y119.136 E.01379
G1 X159.169 Y119.136 E.66174
G1 X159.169 Y118.729 E.01379
M73 P8 R3
M73 Q9 S4
G1 X178.719 Y118.729 E.66174
G1 X178.719 Y118.321 E.01379
M73 P9 R3
M73 Q9 S3
G1 X159.169 Y118.321 E.66174
G1 X159.169 Y117.914 E.01379
G1 X178.719 Y117.914 E.66174
G1 X178.719 Y117.507 E.01379
M73 P10 R3
M73 Q10 S3
G1 X159.169 Y117.507 E.66174
G1 X159.169 Y117.099 E.01379
G1 X178.719 Y117.099 E.66174
G1 X178.719 Y116.692 E.01379
M73 Q11 S3
G1 X159.169 Y116.692 E.66174
G1 X159.169 Y116.285 E.01379
M73 P11 R3
G1 X178.719 Y116.285 E.66174
G1 X178.719 Y115.878 E.01379
G1 X159.169 Y115.878 E.66174
G1 X159.169 Y115.47 E.01379
M73 P12 R3
M73 Q12 S3
G1 X178.719 Y115.47 E.66174
G1 X178.719 Y115.063 E.01379
G1 X159.169 Y115.063 E.66174
G1 X159.169 Y114.656 E.01379
G1 X178.719 Y114.656 E.66174
G1 X178.719 Y114.248 E.01379
M73 P13 R3
M73 Q13 S3
G1 X159.169 Y114.248 E.66174
G1 X159.169 Y113.841 E.01379
G1 X178.719 Y113.841 E.66174
G1 X178.719 Y113.434 E.01379
M73 Q14 S3
G1 X159.169 Y113.434 E.66174
M73 P14 R3
G1 X159.169 Y113.027 E.01379
G1 X178.719 Y113.027 E.66174
G1 X178.719 Y112.619 E.01379
G1 X159.169 Y112.619 E.66174
G1 X159.169 Y112.212 E.01379
M73 P15 R3
M73 Q15 S3
G1 X178.719 Y112.212 E.66174
G1 X178.719 Y111.805 E.01379
G1 X159.169 Y111.805 E.66174
G1 X159.169 Y111.397 E.01379
M73 Q16 S3
G1 X178.719 Y111.397 E.66174
G1 X178.719 Y110.99 E.01379
M73 P16 R3
G1 X159.169 Y110.99 E.66174
G1 X159.169 Y110.583 E.01379
G1 X178.719 Y110.583 E.66174
G1 X178.719 Y110.176 E.01379
M73 P17 R3
M73 Q17 S3
G1 X159.169 Y110.176 E.66174
G1 X159.169 Y109.768 E.01379
G1 X178.719 Y109.768 E.66174
G1 X178.719 Y109.361 E.01379
G1 X159.169 Y109.361 E.66174
G1 X159.169 Y108.954 E.01379
M73 P18 R3
M73 Q18 S3
G1 X178.719 Y108.954 E.66174
G1 X178.719 Y108.546 E.01379
G1 X159.169 Y108.546 E.66174
G1 X159.169 Y108.139 E.01379
M73 P19 R3
M73 Q19 S3
G1 X178.719 Y108.139 E.66174
G1 X178.719 Y107.732 E.01379
G1 X159.169 Y107.732 E.66174
G1 X159.169 Y107.325 E.01379
G1 X178.719 Y107.325 E.66174
G1 X178.719 Y106.917 E.01379
M73 P20 R3
M73 Q20 S3
G1 X159.169 Y106.917 E.66174
G1 X159.169 Y106.51 E.01379
G1 X178.719 Y106.51 E.66174
G1 X178.719 Y106.103 E.01379
M73 Q21 S3
G1 X159.169 Y106.103 E.66174
G1 X159.169 Y105.695 E.01379
M73 P21 R3
G1 X178.903 Y105.695 E.66794
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 3
; printing object shape_002_v11.stl id:0 copy 2

M104 S220 ; set extruder temp
M109 S220 ; wait for extruder temp

;WIPE_START
G1 F8640
G1 X175.611 Y105.695 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
G1 X154.033 Y107.667 F10800
G1 Z.2 F720
M73 Q22 S3
G1 E.8 F2100
M204 S800
G1 F1200
G1 X134.3 Y107.667 E.66794
G1 X134.3 Y108.074 E.01379
M73 P22 R3
G1 X153.85 Y108.074 E.66174
G1 X153.85 Y108.482 E.01379
G1 X134.3 Y108.482 E.66174
G1 X134.3 Y108.889 E.01379
M73 P23 R3
M73 Q23 S3
G1 X153.85 Y108.889 E.66174
G1 X153.85 Y109.296 E.01379
G1 X134.3 Y109.296 E.66174
G1 X134.3 Y109.704 E.01379
G1 X153.85 Y109.704 E.66174
M73 Q24 S3
G1 X153.85 Y110.111 E.01379
M73 P24 R3
G1 X134.3 Y110.111 E.66174
G1 X134.3 Y110.518 E.01379
G1 X153.85 Y110.518 E.66174
G1 X153.85 Y110.926 E.01379
M73 P25 R3
M73 Q25 S3
G1 X134.3 Y110.926 E.66174
G1 X134.3 Y111.333 E.01379
G1 X153.85 Y111.333 E.66174
G1 X153.85 Y111.74 E.01379
G1 X134.3 Y111.74 E.66174
G1 X134.3 Y112.147 E.01379
M73 P26 R3
M73 Q26 S3
G1 X153.85 Y112.147 E.66174
G1 X153.85 Y112.555 E.01379
G1 X134.3 Y112.555 E.66174
G1 X134.3 Y112.962 E.01379
M73 Q27 S3
G1 X153.85 Y112.962 E.66174
G1 X153.85 Y113.369 E.01379
M73 P27 R3
G1 X134.3 Y113.369 E.66174
G1 X134.3 Y113.777 E.01379
G1 X153.85 Y113.777 E.66174
G1 X153.85 Y114.184 E.01379
M73 P28 R3
M73 Q28 S3
G1 X134.3 Y114.184 E.66174
G1 X134.3 Y114.591 E.01379
G1 X153.85 Y114.591 E.66174
G1 X153.85 Y114.998 E.01379
M73 Q29 S3
G1 X134.3 Y114.998 E.66174
G1 X134.3 Y115.406 E.01379
M73 P29 R3
G1 X153.85 Y115.406 E.66174
G1 X153.85 Y115.813 E.01379
G1 X134.3 Y115.813 E.66174
G1 X134.3 Y116.22 E.01379
M73 P30 R3
M73 Q30 S3
G1 X153.85 Y116.22 E.66174
G1 X153.85 Y116.628 E.01379
G1 X134.3 Y116.628 E.66174
G1 X134.3 Y117.035 E.01379
G1 X153.85 Y117.035 E.66174
G1 X153.85 Y117.442 E.01379
M73 P31 R3
M73 Q31 S3
G1 X134.3 Y117.442 E.66174
G1 X134.3 Y117.849 E.01379
G1 X153.85 Y117.849 E.66174
G1 X153.85 Y118.257 E.01379
M73 P31 R2
M73 Q32 S2
G1 X134.3 Y118.257 E.66174
G1 X134.3 Y118.664 E.01379
M73 P32 R2
G1 X153.85 Y118.664 E.66174
G1 X153.85 Y119.071 E.01379
G1 X134.3 Y119.071 E.66174
G1 X134.3 Y119.479 E.01379
M73 P33 R2
M73 Q33 S2
G1 X153.85 Y119.479 E.66174
G1 X153.85 Y119.886 E.01379
G1 X134.3 Y119.886 E.66174
G1 X134.3 Y120.293 E.01379
M73 Q34 S2
G1 X153.85 Y120.293 E.66174
G1 X153.85 Y120.7 E.01379
M73 P34 R2
G1 X134.3 Y120.7 E.66174
G1 X134.3 Y121.108 E.01379
G1 X153.85 Y121.108 E.66174
G1 X153.85 Y121.515 E.01379
M73 P35 R2
M73 Q35 S2
G1 X134.3 Y121.515 E.66174
G1 X134.3 Y121.922 E.01379
G1 X153.85 Y121.922 E.66174
G1 X153.85 Y122.33 E.01379
G1 X134.3 Y122.33 E.66174
G1 X134.3 Y122.737 E.01379
M73 P36 R2
M73 Q36 S2
G1 X153.85 Y122.737 E.66174
G1 X153.85 Y123.144 E.01379
G1 X134.3 Y123.144 E.66174
G1 X134.3 Y123.551 E.01379
M73 Q37 S2
G1 X153.85 Y123.551 E.66174
M73 P37 R2
G1 X153.85 Y123.959 E.01379
G1 X134.3 Y123.959 E.66174
G1 X134.3 Y124.366 E.01379
G1 X153.85 Y124.366 E.66174
G1 X153.85 Y124.773 E.01379
M73 P38 R2
M73 Q38 S2
G1 X134.3 Y124.773 E.66174
G1 X134.3 Y125.181 E.01379
G1 X153.85 Y125.181 E.66174
G1 X153.85 Y125.588 E.01379
M73 Q39 S2
G1 X134.3 Y125.588 E.66174
G1 X134.3 Y125.995 E.01379
M73 P39 R2
G1 X153.85 Y125.995 E.66174
G1 X153.85 Y126.402 E.01379
G1 X134.3 Y126.402 E.66174
G1 X134.3 Y126.81 E.01379
M73 P40 R2
M73 Q40 S2
G1 X153.85 Y126.81 E.66174
G1 X153.85 Y127.217 E.01379
G1 X134.117 Y127.217 E.66794
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 2
; printing object shape_002_v11.stl id:0 copy 0

M104 S230 ; set extruder temp
M109 S230 ; wait for extruder temp

;WIPE_START
G1 F8640
G1 X137.408 Y127.217 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
M73 Q41 S2
G1 X126.004 Y107.477 F10800
G1 Z.2 F720
M73 P41 R2
G1 E.8 F2100
M204 S800
G1 F1200
G1 X106.271 Y107.477 E.66794
G1 X106.271 Y107.884 E.01379
G1 X125.821 Y107.884 E.66174
G1 X125.821 Y108.291 E.01379
G1 X106.271 Y108.291 E.66174
G1 X106.271 Y108.698 E.01379
M73 P42 R2
M73 Q42 S2
G1 X125.821 Y108.698 E.66174
G1 X125.821 Y109.106 E.01379
G1 X106.271 Y109.106 E.66174
G1 X106.271 Y109.513 E.01379
M73 P43 R2
M73 Q43 S2
G1 X125.821 Y109.513 E.66174
G1 X125.821 Y109.92 E.01379
G1 X106.271 Y109.92 E.66174
G1 X106.271 Y110.328 E.01379
G1 X125.821 Y110.328 E.66174
G1 X125.821 Y110.735 E.01379
M73 P44 R2
M73 Q44 S2
G1 X106.271 Y110.735 E.66174
G1 X106.271 Y111.142 E.01379
G1 X125.821 Y111.142 E.66174
G1 X125.821 Y111.549 E.01379
M73 Q45 S2
G1 X106.271 Y111.549 E.66174
G1 X106.271 Y111.957 E.01379
M73 P45 R2
G1 X125.821 Y111.957 E.66174
G1 X125.821 Y112.364 E.01379
G1 X106.271 Y112.364 E.66174
G1 X106.271 Y112.771 E.01379
M73 P46 R2
M73 Q46 S2
G1 X125.821 Y112.771 E.66174
G1 X125.821 Y113.179 E.01379
G1 X106.271 Y113.179 E.66174
G1 X106.271 Y113.586 E.01379
G1 X125.821 Y113.586 E.66174
G1 X125.821 Y113.993 E.01379
M73 P47 R2
M73 Q47 S2
G1 X106.271 Y113.993 E.66174
G1 X106.271 Y114.4 E.01379
G1 X125.821 Y114.4 E.66174
G1 X125.821 Y114.808 E.01379
M73 P48 R2
M73 Q48 S2
G1 X106.271 Y114.808 E.66174
G1 X106.271 Y115.215 E.01379
G1 X125.821 Y115.215 E.66174
G1 X125.821 Y115.622 E.01379
G1 X106.271 Y115.622 E.66174
G1 X106.271 Y116.03 E.01379
M73 P49 R2
M73 Q49 S2
G1 X125.821 Y116.03 E.66174
G1 X125.821 Y116.437 E.01379
G1 X106.271 Y116.437 E.66174
G1 X106.271 Y116.844 E.01379
M73 Q50 S2
G1 X125.821 Y116.844 E.66174
G1 X125.821 Y117.251 E.01379
M73 P50 R2
G1 X106.271 Y117.251 E.66174
G1 X106.271 Y117.659 E.01379
G1 X125.821 Y117.659 E.66174
G1 X125.821 Y118.066 E.01379
M73 P51 R2
M73 Q51 S2
G1 X106.271 Y118.066 E.66174
G1 X106.271 Y118.473 E.01379
G1 X125.821 Y118.473 E.66174
G1 X125.821 Y118.881 E.01379
G1 X106.271 Y118.881 E.66174
G1 X106.271 Y119.288 E.01379
M73 P52 R2
M73 Q52 S2
G1 X125.821 Y119.288 E.66174
G1 X125.821 Y119.695 E.01379
G1 X106.271 Y119.695 E.66174
G1 X106.271 Y120.102 E.01379
M73 P53 R2
M73 Q53 S2
G1 X125.821 Y120.102 E.66174
G1 X125.821 Y120.51 E.01379
G1 X106.271 Y120.51 E.66174
G1 X106.271 Y120.917 E.01379
G1 X125.821 Y120.917 E.66174
G1 X125.821 Y121.324 E.01379
M73 P54 R2
M73 Q54 S2
G1 X106.271 Y121.324 E.66174
G1 X106.271 Y121.732 E.01379
M73 P54 R1
M73 Q54 S1
G1 X125.821 Y121.732 E.66174
G1 X125.821 Y122.139 E.01379
M73 Q55 S1
G1 X106.271 Y122.139 E.66174
G1 X106.271 Y122.546 E.01379
M73 P55 R1
G1 X125.821 Y122.546 E.66174
G1 X125.821 Y122.953 E.01379
G1 X106.271 Y122.953 E.66174
G1 X106.271 Y123.361 E.01379
M73 P56 R1
M73 Q56 S1
G1 X125.821 Y123.361 E.66174
G1 X125.821 Y123.768 E.01379
G1 X106.271 Y123.768 E.66174
G1 X106.271 Y124.175 E.01379
G1 X125.821 Y124.175 E.66174
G1 X125.821 Y124.583 E.01379
M73 P57 R1
M73 Q57 S1
G1 X106.271 Y124.583 E.66174
G1 X106.271 Y124.99 E.01379
G1 X125.821 Y124.99 E.66174
G1 X125.821 Y125.397 E.01379
M73 P58 R1
M73 Q58 S1
G1 X106.271 Y125.397 E.66174
G1 X106.271 Y125.804 E.01379
G1 X125.821 Y125.804 E.66174
G1 X125.821 Y126.212 E.01379
G1 X106.271 Y126.212 E.66174
G1 X106.271 Y126.619 E.01379
M73 P59 R1
M73 Q59 S1
G1 X125.821 Y126.619 E.66174
G1 X125.821 Y127.026 E.01379
G1 X106.087 Y127.026 E.66794
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 0
; printing object shape_002_v11.stl id:0 copy 1

M104 S240 ; set extruder temp
M109 S240 ; wait for extruder temp

;WIPE_START
G1 F8640
M73 P60 R1
M73 Q60 S1
G1 X109.379 Y127.026 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
G1 X100.809 Y108.012 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
G1 F1200
G1 X81.076 Y108.012 E.66794
G1 X81.076 Y108.419 E.01379
G1 X100.626 Y108.419 E.66174
G1 X100.626 Y108.826 E.01379
M73 Q61 S1
G1 X81.076 Y108.826 E.66174
G1 X81.076 Y109.233 E.01379
M73 P61 R1
G1 X100.626 Y109.233 E.66174
G1 X100.626 Y109.641 E.01379
G1 X81.076 Y109.641 E.66174
G1 X81.076 Y110.048 E.01379
M73 P62 R1
M73 Q62 S1
G1 X100.626 Y110.048 E.66174
G1 X100.626 Y110.455 E.01379
G1 X81.076 Y110.455 E.66174
G1 X81.076 Y110.863 E.01379
G1 X100.626 Y110.863 E.66174
G1 X100.626 Y111.27 E.01379
M73 P63 R1
M73 Q63 S1
G1 X81.076 Y111.27 E.66174
G1 X81.076 Y111.677 E.01379
G1 X100.626 Y111.677 E.66174
G1 X100.626 Y112.084 E.01379
M73 P64 R1
M73 Q64 S1
G1 X81.076 Y112.084 E.66174
G1 X81.076 Y112.492 E.01379
G1 X100.626 Y112.492 E.66174
G1 X100.626 Y112.899 E.01379
G1 X81.076 Y112.899 E.66174
G1 X81.076 Y113.306 E.01379
M73 P65 R1
M73 Q65 S1
G1 X100.626 Y113.306 E.66174
G1 X100.626 Y113.714 E.01379
G1 X81.076 Y113.714 E.66174
G1 X81.076 Y114.121 E.01379
M73 P66 R1
M73 Q66 S1
G1 X100.626 Y114.121 E.66174
G1 X100.626 Y114.528 E.01379
G1 X81.076 Y114.528 E.66174
G1 X81.076 Y114.935 E.01379
G1 X100.626 Y114.935 E.66174
G1 X100.626 Y115.343 E.01379
M73 P67 R1
M73 Q67 S1
G1 X81.076 Y115.343 E.66174
G1 X81.076 Y115.75 E.01379
G1 X100.626 Y115.75 E.66174
G1 X100.626 Y116.157 E.01379
G1 X81.076 Y116.157 E.66174
M73 Q68 S1
G1 X81.076 Y116.565 E.01379
M73 P68 R1
G1 X100.626 Y116.565 E.66174
G1 X100.626 Y116.972 E.01379
G1 X81.076 Y116.972 E.66174
G1 X81.076 Y117.379 E.01379
M73 P69 R1
M73 Q69 S1
G1 X100.626 Y117.379 E.66174
G1 X100.626 Y117.786 E.01379
G1 X81.076 Y117.786 E.66174
G1 X81.076 Y118.194 E.01379
G1 X100.626 Y118.194 E.66174
G1 X100.626 Y118.601 E.01379
M73 P70 R1
M73 Q70 S1
G1 X81.076 Y118.601 E.66174
G1 X81.076 Y119.008 E.01379
G1 X100.626 Y119.008 E.66174
G1 X100.626 Y119.416 E.01379
M73 P71 R1
M73 Q71 S1
G1 X81.076 Y119.416 E.66174
G1 X81.076 Y119.823 E.01379
G1 X100.626 Y119.823 E.66174
G1 X100.626 Y120.23 E.01379
G1 X81.076 Y120.23 E.66174
G1 X81.076 Y120.637 E.01379
M73 P72 R1
M73 Q72 S1
G1 X100.626 Y120.637 E.66174
G1 X100.626 Y121.045 E.01379
G1 X81.076 Y121.045 E.66174
G1 X81.076 Y121.452 E.01379
M73 Q73 S1
G1 X100.626 Y121.452 E.66174
G1 X100.626 Y121.859 E.01379
M73 P73 R1
G1 X81.076 Y121.859 E.66174
G1 X81.076 Y122.267 E.01379
G1 X100.626 Y122.267 E.66174
G1 X100.626 Y122.674 E.01379
M73 P74 R1
M73 Q74 S1
G1 X81.076 Y122.674 E.66174
G1 X81.076 Y123.081 E.01379
G1 X100.626 Y123.081 E.66174
G1 X100.626 Y123.488 E.01379
G1 X81.076 Y123.488 E.66174
G1 X81.076 Y123.896 E.01379
M73 P75 R1
M73 Q75 S1
G1 X100.626 Y123.896 E.66174
G1 X100.626 Y124.303 E.01379
G1 X81.076 Y124.303 E.66174
G1 X81.076 Y124.71 E.01379
M73 P76 R1
M73 Q76 S1
G1 X100.626 Y124.71 E.66174
G1 X100.626 Y125.118 E.01379
G1 X81.076 Y125.118 E.66174
G1 X81.076 Y125.525 E.01379
G1 X100.626 Y125.525 E.66174
G1 X100.626 Y125.932 E.01379
M73 P77 R1
M73 Q77 S1
G1 X81.076 Y125.932 E.66174
G1 X81.076 Y126.34 E.01379
M73 P77 R0
M73 Q77 S0
G1 X100.626 Y126.34 E.66174
G1 X100.626 Y126.747 E.01379
M73 Q78 S0
G1 X81.076 Y126.747 E.66174
G1 X81.076 Y127.154 E.01379
M73 P78 R0
G1 X100.626 Y127.154 E.66174
G1 X100.626 Y127.561 E.01379
G1 X80.892 Y127.561 E.66794
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 1
; printing object shape_002_v11.stl id:0 copy 4

M104 S250 ; set extruder temp
M109 S250 ; wait for extruder temp

;WIPE_START
G1 F8640
M73 P79 R0
M73 Q79 S0
G1 X84.184 Y127.561 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
G1 X73.59 Y107.751 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
G1 F1200
G1 X53.857 Y107.751 E.66794
G1 X53.857 Y108.158 E.01379
G1 X73.407 Y108.158 E.66174
G1 X73.407 Y108.565 E.01379
M73 P80 R0
M73 Q80 S0
G1 X53.857 Y108.565 E.66174
G1 X53.857 Y108.973 E.01379
G1 X73.407 Y108.973 E.66174
G1 X73.407 Y109.38 E.01379
G1 X53.857 Y109.38 E.66174
G1 X53.857 Y109.787 E.01379
M73 P81 R0
M73 Q81 S0
G1 X73.407 Y109.787 E.66174
G1 X73.407 Y110.194 E.01379
G1 X53.857 Y110.194 E.66174
G1 X53.857 Y110.602 E.01379
M73 P82 R0
M73 Q82 S0
G1 X73.407 Y110.602 E.66174
G1 X73.407 Y111.009 E.01379
G1 X53.857 Y111.009 E.66174
G1 X53.857 Y111.416 E.01379
G1 X73.407 Y111.416 E.66174
G1 X73.407 Y111.824 E.01379
M73 P83 R0
M73 Q83 S0
G1 X53.857 Y111.824 E.66174
G1 X53.857 Y112.231 E.01379
G1 X73.407 Y112.231 E.66174
G1 X73.407 Y112.638 E.01379
M73 Q84 S0
G1 X53.857 Y112.638 E.66174
G1 X53.857 Y113.045 E.01379
M73 P84 R0
G1 X73.407 Y113.045 E.66174
G1 X73.407 Y113.453 E.01379
G1 X53.857 Y113.453 E.66174
G1 X53.857 Y113.86 E.01379
M73 P85 R0
M73 Q85 S0
G1 X73.407 Y113.86 E.66174
G1 X73.407 Y114.267 E.01379
G1 X53.857 Y114.267 E.66174
G1 X53.857 Y114.675 E.01379
G1 X73.407 Y114.675 E.66174
G1 X73.407 Y115.082 E.01379
M73 P86 R0
M73 Q86 S0
G1 X53.857 Y115.082 E.66174
G1 X53.857 Y115.489 E.01379
G1 X73.407 Y115.489 E.66174
G1 X73.407 Y115.896 E.01379
M73 P87 R0
M73 Q87 S0
G1 X53.857 Y115.896 E.66174
G1 X53.857 Y116.304 E.01379
G1 X73.407 Y116.304 E.66174
G1 X73.407 Y116.711 E.01379
G1 X53.857 Y116.711 E.66174
G1 X53.857 Y117.118 E.01379
M73 P88 R0
M73 Q88 S0
G1 X73.407 Y117.118 E.66174
G1 X73.407 Y117.526 E.01379
G1 X53.857 Y117.526 E.66174
G1 X53.857 Y117.933 E.01379
M73 P89 R0
M73 Q89 S0
G1 X73.407 Y117.933 E.66174
G1 X73.407 Y118.34 E.01379
G1 X53.857 Y118.34 E.66174
G1 X53.857 Y118.747 E.01379
G1 X73.407 Y118.747 E.66174
G1 X73.407 Y119.155 E.01379
M73 P90 R0
M73 Q90 S0
G1 X53.857 Y119.155 E.66174
G1 X53.857 Y119.562 E.01379
G1 X73.407 Y119.562 E.66174
G1 X73.407 Y119.969 E.01379
G1 X53.857 Y119.969 E.66174
G1 X53.857 Y120.377 E.01379
M73 P91 R0
M73 Q91 S0
G1 X73.407 Y120.377 E.66174
G1 X73.407 Y120.784 E.01379
G1 X53.857 Y120.784 E.66174
G1 X53.857 Y121.191 E.01379
M73 P92 R0
M73 Q92 S0
G1 X73.407 Y121.191 E.66174
G1 X73.407 Y121.598 E.01379
G1 X53.857 Y121.598 E.66174
G1 X53.857 Y122.006 E.01379
G1 X73.407 Y122.006 E.66174
G1 X73.407 Y122.413 E.01379
M73 P93 R0
M73 Q93 S0
G1 X53.857 Y122.413 E.66174
G1 X53.857 Y122.82 E.01379
G1 X73.407 Y122.82 E.66174
G1 X73.407 Y123.228 E.01379
M73 P94 R0
M73 Q94 S0
G1 X53.857 Y123.228 E.66174
G1 X53.857 Y123.635 E.01379
G1 X73.407 Y123.635 E.66174
G1 X73.407 Y124.042 E.01379
G1 X53.857 Y124.042 E.66174
G1 X53.857 Y124.449 E.01379
M73 P95 R0
M73 Q95 S0
G1 X73.407 Y124.449 E.66174
G1 X73.407 Y124.857 E.01379
G1 X53.857 Y124.857 E.66174
G1 X53.857 Y125.264 E.01379
G1 X73.407 Y125.264 E.66174
G1 X73.407 Y125.671 E.01379
M73 P96 R0
M73 Q96 S0
G1 X53.857 Y125.671 E.66174
G1 X53.857 Y126.079 E.01379
G1 X73.407 Y126.079 E.66174
G1 X73.407 Y126.486 E.01379
M73 P97 R0
M73 Q97 S0
G1 X53.857 Y126.486 E.66174
G1 X53.857 Y126.893 E.01379
G1 X73.407 Y126.893 E.66174
G1 X73.407 Y127.301 E.01379
G1 X53.673 Y127.301 E.66794
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 4
;WIPE_START
G1 F8640;_WIPE
M73 P98 R0
M73 Q98 S0
G1 X56.965 Y127.301 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.2 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 165.50
; filament used [cm3] = 0.40
; filament used [g] = 0.49
; filament cost = 0.02
; total filament used [g] = 0.49
; total filament cost = 0.02
; estimated printing time (normal mode) = 4m 23s
; estimated printing time (silent mode) = 4m 23s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 30
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 0
; bridge_flow_ratio = 0.95
; bridge_speed = 20
; brim_separation = 0.1
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 20
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "VarioShore TPU bed30"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = FLEX
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 0
; fill_density = 100%
; fill_pattern = alignedrectilinear
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 30
; first_layer_extrusion_width = 0.45
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 210
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 20
; inherits_cummulative = "0.20mm QUALITY @MK3";"Prusament PLA";
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 0
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 20
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 0
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 22
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 20
; perimeters = 0
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm VarioSore
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 0
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 0
; small_perimeter_speed = 20
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 22
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.10.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 22
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 20
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 0
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 172.332
; wipe_tower_y = 137.841
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
