; generated by PrusaSlicer 2.4.2+win64 on 2022-09-09 at 12:17:05 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.45mm

M73 P0 R2
M73 Q0 S2
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.10.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S240 ; set extruder temp
M140 S40 ; set bed temp
M190 S40 ; wait for bed temp
M109 S240 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P2 R2
M73 Q2 S2
G1 E-.8 F2100
M73 P3 R2
M73 Q3 S2
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.2
; printing object shape_002_v11.stl id:0 copy 2
G1 X128.02 Y114.796 F10800
G1 Z.2 F720
M73 P4 R2
M73 Q4 S2
G1 E.8 F2100
M204 S800
;TYPE:Internal infill
;WIDTH:0.45
G1 F1200
G1 X147.796 Y114.796 E.6694
G1 X147.796 Y114.388 E.01382
M73 P5 R2
M73 Q5 S2
G1 X128.204 Y114.388 E.6632
G1 X128.204 Y113.98 E.01382
G1 X147.796 Y113.98 E.6632
G1 X147.796 Y113.571 E.01382
M73 P6 R2
M73 Q6 S2
G1 X128.204 Y113.571 E.6632
G1 X128.204 Y113.163 E.01382
M73 Q7 S2
G1 X147.796 Y113.163 E.6632
G1 X147.796 Y112.755 E.01382
M73 P7 R2
G1 X128.204 Y112.755 E.6632
G1 X128.204 Y112.347 E.01382
M73 P8 R2
M73 Q8 S2
G1 X147.796 Y112.347 E.6632
G1 X147.796 Y111.939 E.01382
G1 X128.204 Y111.939 E.6632
M73 Q9 S2
G1 X128.204 Y111.531 E.01382
M73 P9 R2
G1 X147.796 Y111.531 E.6632
G1 X147.796 Y111.122 E.01382
M73 Q10 S2
G1 X128.204 Y111.122 E.6632
M73 P10 R2
G1 X128.204 Y110.714 E.01382
G1 X147.796 Y110.714 E.6632
G1 X147.796 Y110.306 E.01382
M73 P11 R2
M73 Q11 S2
G1 X128.204 Y110.306 E.6632
G1 X128.204 Y109.898 E.01382
M73 Q12 S2
G1 X147.796 Y109.898 E.6632
G1 X147.796 Y109.49 E.01382
M73 P12 R2
G1 X128.204 Y109.49 E.6632
G1 X128.204 Y109.082 E.01382
M73 P13 R2
M73 Q13 S2
G1 X147.796 Y109.082 E.6632
G1 X147.796 Y108.674 E.01382
G1 X128.204 Y108.674 E.6632
G1 X128.204 Y108.265 E.01382
M73 P14 R2
M73 Q14 S2
G1 X147.796 Y108.265 E.6632
G1 X147.796 Y107.857 E.01382
M73 Q15 S2
G1 X128.204 Y107.857 E.6632
G1 X128.204 Y107.449 E.01382
M73 P15 R2
G1 X147.796 Y107.449 E.6632
G1 X147.796 Y107.041 E.01382
M73 P16 R2
M73 Q16 S2
G1 X128.204 Y107.041 E.6632
G1 X128.204 Y106.633 E.01382
M73 Q17 S2
G1 X147.796 Y106.633 E.6632
G1 X147.796 Y106.225 E.01382
M73 P17 R2
G1 X128.204 Y106.225 E.6632
G1 X128.204 Y105.816 E.01382
M73 P18 R2
M73 Q18 S2
G1 X147.796 Y105.816 E.6632
G1 X147.796 Y105.408 E.01382
G1 X128.204 Y105.408 E.6632
G1 X128.204 Y105 E.01382
M73 P19 R2
M73 Q19 S2
G1 X147.796 Y105 E.6632
G1 X147.796 Y104.592 E.01382
M73 Q20 S2
G1 X128.204 Y104.592 E.6632
G1 X128.204 Y104.184 E.01382
M73 P20 R2
G1 X147.796 Y104.184 E.6632
G1 X147.796 Y103.776 E.01382
M73 P21 R2
M73 Q21 S2
G1 X128.204 Y103.776 E.6632
G1 X128.204 Y103.367 E.01382
G1 X147.796 Y103.367 E.6632
G1 X147.796 Y102.959 E.01382
M73 P22 R2
M73 Q22 S2
G1 X128.204 Y102.959 E.6632
G1 X128.204 Y102.551 E.01382
M73 P23 R2
M73 Q23 S2
G1 X147.796 Y102.551 E.6632
G1 X147.796 Y102.143 E.01382
G1 X128.204 Y102.143 E.6632
G1 X128.204 Y101.735 E.01382
M73 P24 R2
M73 Q24 S2
G1 X147.796 Y101.735 E.6632
G1 X147.796 Y101.327 E.01382
M73 Q25 S2
G1 X128.204 Y101.327 E.6632
G1 X128.204 Y100.918 E.01382
M73 P25 R2
G1 X147.796 Y100.918 E.6632
G1 X147.796 Y100.51 E.01382
M73 P26 R2
M73 Q26 S2
G1 X128.204 Y100.51 E.6632
G1 X128.204 Y100.102 E.01382
G1 X147.796 Y100.102 E.6632
G1 X147.796 Y99.694 E.01382
M73 P27 R1
M73 Q27 S1
G1 X128.204 Y99.694 E.6632
G1 X128.204 Y99.286 E.01382
M73 Q28 S1
G1 X147.796 Y99.286 E.6632
G1 X147.796 Y98.878 E.01382
M73 P28 R1
G1 X128.204 Y98.878 E.6632
G1 X128.204 Y98.469 E.01382
M73 P29 R1
M73 Q29 S1
G1 X147.796 Y98.469 E.6632
G1 X147.796 Y98.061 E.01382
M73 Q30 S1
G1 X128.204 Y98.061 E.6632
G1 X128.204 Y97.653 E.01382
M73 P30 R1
G1 X147.796 Y97.653 E.6632
G1 X147.796 Y97.245 E.01382
M73 P31 R1
M73 Q31 S1
G1 X128.204 Y97.245 E.6632
G1 X128.204 Y96.837 E.01382
G1 X147.796 Y96.837 E.6632
G1 X147.796 Y96.429 E.01382
M73 P32 R1
M73 Q32 S1
G1 X128.204 Y96.429 E.6632
G1 X128.204 Y96.02 E.01382
M73 Q33 S1
G1 X147.796 Y96.02 E.6632
G1 X147.796 Y95.612 E.01382
M73 P33 R1
G1 X128.204 Y95.612 E.6632
G1 X128.204 Y95.204 E.01382
M73 P34 R1
M73 Q34 S1
G1 X147.98 Y95.204 E.6694
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 2
; printing object shape_002_v11.stl id:0 copy 1
;WIPE_START
G1 F8640
G1 X144.688 Y95.204 E-.76
;WIPE_END
G1 E-.04 F2100
M73 Q35 S1
G1 Z.6 F720
G1 X121.98 Y108.204 F10800
G1 Z.2 F720
M73 P35 R1
G1 E.8 F2100
M204 S800
G1 F1200
G1 X102.204 Y108.204 E.6694
G1 X102.204 Y108.612 E.01382
G1 X121.796 Y108.612 E.6632
G1 X121.796 Y109.02 E.01382
M73 P36 R1
M73 Q36 S1
G1 X102.204 Y109.02 E.6632
G1 X102.204 Y109.429 E.01382
M73 P37 R1
M73 Q37 S1
G1 X121.796 Y109.429 E.6632
G1 X121.796 Y109.837 E.01382
G1 X102.204 Y109.837 E.6632
G1 X102.204 Y110.245 E.01382
M73 P38 R1
M73 Q38 S1
G1 X121.796 Y110.245 E.6632
G1 X121.796 Y110.653 E.01382
M73 Q39 S1
G1 X102.204 Y110.653 E.6632
G1 X102.204 Y111.061 E.01382
M73 P39 R1
G1 X121.796 Y111.061 E.6632
G1 X121.796 Y111.469 E.01382
M73 P40 R1
M73 Q40 S1
G1 X102.204 Y111.469 E.6632
G1 X102.204 Y111.878 E.01382
G1 X121.796 Y111.878 E.6632
G1 X121.796 Y112.286 E.01382
M73 P41 R1
M73 Q41 S1
G1 X102.204 Y112.286 E.6632
G1 X102.204 Y112.694 E.01382
M73 Q42 S1
G1 X121.796 Y112.694 E.6632
M73 P42 R1
G1 X121.796 Y113.102 E.01382
G1 X102.204 Y113.102 E.6632
G1 X102.204 Y113.51 E.01382
M73 P43 R1
M73 Q43 S1
G1 X121.796 Y113.51 E.6632
G1 X121.796 Y113.918 E.01382
G1 X102.204 Y113.918 E.6632
M73 Q44 S1
G1 X102.204 Y114.327 E.01382
M73 P44 R1
G1 X121.796 Y114.327 E.6632
G1 X121.796 Y114.735 E.01382
M73 P45 R1
M73 Q45 S1
G1 X102.204 Y114.735 E.6632
G1 X102.204 Y115.143 E.01382
G1 X121.796 Y115.143 E.6632
G1 X121.796 Y115.551 E.01382
M73 P46 R1
M73 Q46 S1
G1 X102.204 Y115.551 E.6632
G1 X102.204 Y115.959 E.01382
M73 Q47 S1
G1 X121.796 Y115.959 E.6632
G1 X121.796 Y116.367 E.01382
M73 P47 R1
G1 X102.204 Y116.367 E.6632
G1 X102.204 Y116.776 E.01382
M73 P48 R1
M73 Q48 S1
G1 X121.796 Y116.776 E.6632
G1 X121.796 Y117.184 E.01382
G1 X102.204 Y117.184 E.6632
G1 X102.204 Y117.592 E.01382
M73 P49 R1
M73 Q49 S1
G1 X121.796 Y117.592 E.6632
G1 X121.796 Y118 E.01382
M73 P50 R1
M73 Q50 S1
G1 X102.204 Y118 E.6632
G1 X102.204 Y118.408 E.01382
G1 X121.796 Y118.408 E.6632
G1 X121.796 Y118.816 E.01382
M73 P51 R1
M73 Q51 S1
G1 X102.204 Y118.816 E.6632
G1 X102.204 Y119.225 E.01382
M73 Q52 S1
G1 X121.796 Y119.225 E.6632
G1 X121.796 Y119.633 E.01382
M73 P52 R1
G1 X102.204 Y119.633 E.6632
G1 X102.204 Y120.041 E.01382
M73 P53 R1
M73 Q53 S1
G1 X121.796 Y120.041 E.6632
G1 X121.796 Y120.449 E.01382
G1 X102.204 Y120.449 E.6632
G1 X102.204 Y120.857 E.01382
M73 P54 R1
M73 Q54 S1
G1 X121.796 Y120.857 E.6632
G1 X121.796 Y121.265 E.01382
M73 P55 R1
M73 Q55 S1
G1 X102.204 Y121.265 E.6632
G1 X102.204 Y121.674 E.01382
G1 X121.796 Y121.674 E.6632
G1 X121.796 Y122.082 E.01382
M73 P56 R1
M73 Q56 S1
G1 X102.204 Y122.082 E.6632
G1 X102.204 Y122.49 E.01382
G1 X121.796 Y122.49 E.6632
M73 Q57 S1
G1 X121.796 Y122.898 E.01382
M73 P57 R1
G1 X102.204 Y122.898 E.6632
G1 X102.204 Y123.306 E.01382
M73 P58 R1
M73 Q58 S1
G1 X121.796 Y123.306 E.6632
G1 X121.796 Y123.714 E.01382
G1 X102.204 Y123.714 E.6632
G1 X102.204 Y124.122 E.01382
M73 P59 R1
M73 Q59 S1
G1 X121.796 Y124.122 E.6632
G1 X121.796 Y124.531 E.01382
M73 Q60 S1
G1 X102.204 Y124.531 E.6632
G1 X102.204 Y124.939 E.01382
M73 P60 R1
G1 X121.796 Y124.939 E.6632
G1 X121.796 Y125.347 E.01382
M73 P61 R1
M73 Q61 S1
G1 X102.204 Y125.347 E.6632
G1 X102.204 Y125.755 E.01382
G1 X121.796 Y125.755 E.6632
G1 X121.796 Y126.163 E.01382
M73 P62 R1
M73 Q62 S1
G1 X102.204 Y126.163 E.6632
G1 X102.204 Y126.571 E.01382
M73 P63 R1
M73 Q63 S1
G1 X121.796 Y126.571 E.6632
G1 X121.796 Y126.98 E.01382
G1 X102.204 Y126.98 E.6632
G1 X102.204 Y127.388 E.01382
M73 P64 R0
M73 Q64 S0
G1 X121.796 Y127.388 E.6632
G1 X121.796 Y127.796 E.01382
M73 Q65 S0
G1 X102.02 Y127.796 E.6694
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 1
; printing object shape_002_v11.stl id:0 copy 0
;WIPE_START
G1 F8640
M73 P65 R0
G1 X105.312 Y127.796 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
G1 X102.02 Y101.796 F10800
G1 Z.2 F720
G1 E.8 F2100
M204 S800
M73 Q66 S0
G1 F1200
G1 X121.796 Y101.796 E.6694
G1 X121.796 Y101.388 E.01382
M73 P66 R0
G1 X102.204 Y101.388 E.6632
G1 X102.204 Y100.98 E.01382
M73 P67 R0
M73 Q67 S0
G1 X121.796 Y100.98 E.6632
G1 X121.796 Y100.571 E.01382
G1 X102.204 Y100.571 E.6632
G1 X102.204 Y100.163 E.01382
M73 P68 R0
M73 Q68 S0
G1 X121.796 Y100.163 E.6632
G1 X121.796 Y99.755 E.01382
M73 P69 R0
M73 Q69 S0
G1 X102.204 Y99.755 E.6632
G1 X102.204 Y99.347 E.01382
G1 X121.796 Y99.347 E.6632
G1 X121.796 Y98.939 E.01382
M73 P70 R0
M73 Q70 S0
G1 X102.204 Y98.939 E.6632
G1 X102.204 Y98.531 E.01382
G1 X121.796 Y98.531 E.6632
G1 X121.796 Y98.122 E.01382
M73 P71 R0
M73 Q71 S0
G1 X102.204 Y98.122 E.6632
G1 X102.204 Y97.714 E.01382
M73 P72 R0
M73 Q72 S0
G1 X121.796 Y97.714 E.6632
G1 X121.796 Y97.306 E.01382
G1 X102.204 Y97.306 E.6632
G1 X102.204 Y96.898 E.01382
M73 P73 R0
M73 Q73 S0
G1 X121.796 Y96.898 E.6632
G1 X121.796 Y96.49 E.01382
M73 Q74 S0
G1 X102.204 Y96.49 E.6632
M73 P74 R0
G1 X102.204 Y96.082 E.01382
G1 X121.796 Y96.082 E.6632
G1 X121.796 Y95.674 E.01382
M73 P75 R0
M73 Q75 S0
G1 X102.204 Y95.674 E.6632
G1 X102.204 Y95.265 E.01382
G1 X121.796 Y95.265 E.6632
G1 X121.796 Y94.857 E.01382
M73 P76 R0
M73 Q76 S0
G1 X102.204 Y94.857 E.6632
G1 X102.204 Y94.449 E.01382
M73 P77 R0
M73 Q77 S0
G1 X121.796 Y94.449 E.6632
G1 X121.796 Y94.041 E.01382
G1 X102.204 Y94.041 E.6632
G1 X102.204 Y93.633 E.01382
M73 P78 R0
M73 Q78 S0
G1 X121.796 Y93.633 E.6632
G1 X121.796 Y93.225 E.01382
M73 Q79 S0
G1 X102.204 Y93.225 E.6632
G1 X102.204 Y92.816 E.01382
M73 P79 R0
G1 X121.796 Y92.816 E.6632
G1 X121.796 Y92.408 E.01382
M73 P80 R0
M73 Q80 S0
G1 X102.204 Y92.408 E.6632
G1 X102.204 Y92 E.01382
G1 X121.796 Y92 E.6632
G1 X121.796 Y91.592 E.01382
M73 P81 R0
M73 Q81 S0
G1 X102.204 Y91.592 E.6632
G1 X102.204 Y91.184 E.01382
M73 P82 R0
M73 Q82 S0
G1 X121.796 Y91.184 E.6632
G1 X121.796 Y90.776 E.01382
G1 X102.204 Y90.776 E.6632
G1 X102.204 Y90.367 E.01382
M73 P83 R0
M73 Q83 S0
G1 X121.796 Y90.367 E.6632
G1 X121.796 Y89.959 E.01382
G1 X102.204 Y89.959 E.6632
G1 X102.204 Y89.551 E.01382
M73 P84 R0
M73 Q84 S0
G1 X121.796 Y89.551 E.6632
G1 X121.796 Y89.143 E.01382
M73 P85 R0
M73 Q85 S0
G1 X102.204 Y89.143 E.6632
G1 X102.204 Y88.735 E.01382
G1 X121.796 Y88.735 E.6632
G1 X121.796 Y88.327 E.01382
M73 P86 R0
M73 Q86 S0
G1 X102.204 Y88.327 E.6632
G1 X102.204 Y87.918 E.01382
M73 P87 R0
M73 Q87 S0
G1 X121.796 Y87.918 E.6632
G1 X121.796 Y87.51 E.01382
G1 X102.204 Y87.51 E.6632
G1 X102.204 Y87.102 E.01382
M73 P88 R0
M73 Q88 S0
G1 X121.796 Y87.102 E.6632
G1 X121.796 Y86.694 E.01382
G1 X102.204 Y86.694 E.6632
G1 X102.204 Y86.286 E.01382
M73 P89 R0
M73 Q89 S0
G1 X121.796 Y86.286 E.6632
G1 X121.796 Y85.878 E.01382
M73 P90 R0
M73 Q90 S0
G1 X102.204 Y85.878 E.6632
G1 X102.204 Y85.469 E.01382
G1 X121.796 Y85.469 E.6632
G1 X121.796 Y85.061 E.01382
M73 P91 R0
M73 Q91 S0
G1 X102.204 Y85.061 E.6632
G1 X102.204 Y84.653 E.01382
M73 Q92 S0
G1 X121.796 Y84.653 E.6632
G1 X121.796 Y84.245 E.01382
M73 P92 R0
G1 X102.204 Y84.245 E.6632
G1 X102.204 Y83.837 E.01382
M73 P93 R0
M73 Q93 S0
G1 X121.796 Y83.837 E.6632
G1 X121.796 Y83.429 E.01382
G1 X102.204 Y83.429 E.6632
G1 X102.204 Y83.02 E.01382
M73 P94 R0
M73 Q94 S0
G1 X121.796 Y83.02 E.6632
G1 X121.796 Y82.612 E.01382
M73 P95 R0
M73 Q95 S0
G1 X102.204 Y82.612 E.6632
G1 X102.204 Y82.204 E.01382
G1 X121.98 Y82.204 E.6694
M204 S1000
; stop printing object shape_002_v11.stl id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
M73 P96 R0
M73 Q96 S0
G1 X118.688 Y82.204 E-.76
;WIPE_END
G1 E-.04 F2100
G1 Z.6 F720
M107
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.2 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 99.52
; filament used [cm3] = 0.24
; filament used [g] = 0.30
; filament cost = 0.01
; total filament used [g] = 0.30
; total filament cost = 0.01
; estimated printing time (normal mode) = 2m 44s
; estimated printing time (silent mode) = 2m 44s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 40
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 0
; bridge_flow_ratio = 0.95
; bridge_speed = 20
; brim_separation = 0.1
; brim_type = no_brim
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 20
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Affordable filament for everyday printing in premium quality manufactured in-house by Josef Prusa"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "VarioShore TPU"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = FLEX
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 0
; fill_density = 100%
; fill_pattern = alignedrectilinear
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 40
; first_layer_extrusion_width = 0.45
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 240
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 20
; inherits_cummulative = "0.20mm QUALITY @MK3";"Prusament PLA";
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 0
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 20
; max_volumetric_speed = 0
; min_fan_speed = 0
; min_layer_height = 0.07
; min_print_speed = 22
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_speed = 20
; perimeters = 0
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm VarioSore
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = nearest
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 0
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 0
; small_perimeter_speed = 20
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 22
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.10.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 22
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 240
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 20
; thumbnails = 
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 0
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 172.332
; wipe_tower_y = 137.841
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
